package com.archivenexus.backend.archiveos.runtime;

import com.archivenexus.backend.outbox.OutboxEventEntity;
import com.archivenexus.backend.outbox.OutboxModels.EventType;
import com.archivenexus.backend.outbox.OutboxModels.OutboxTargetService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service
public class ArchiveOsRuntimeDeliveryService {
    private static final Set<EventType> OBSERVABLE=EnumSet.of(EventType.MATERIAL_CONSUMED,EventType.QUALITY_INSPECTION_COMPLETED,EventType.PRODUCTION_COMPLETED,EventType.PRODUCTION_DELAYED,EventType.LOGISTICS_DISPATCHED,EventType.SHIPMENT_HOLD_CREATED,EventType.SHIPMENT_HOLD_RELEASED,EventType.QUALITY_DEFECT_DETECTED,EventType.MAINTENANCE_REQUIRED,EventType.MAINTENANCE_COMPLETED,EventType.BACKLOG_INCREASED);
    private final ArchiveOsRuntimeDeliveryRepository repository; private final ArchiveOsRuntimePublisher publisher; private final ArchiveOsRuntimeProperties properties; private final ObjectMapper mapper;
    public ArchiveOsRuntimeDeliveryService(ArchiveOsRuntimeDeliveryRepository repository,ArchiveOsRuntimePublisher publisher,ArchiveOsRuntimeProperties properties,ObjectMapper mapper){this.repository=repository;this.publisher=publisher;this.properties=properties;this.mapper=mapper;}
    @Transactional(propagation=Propagation.REQUIRES_NEW)
    public void snapshotOutbox(OutboxEventEntity event){ if(!OBSERVABLE.contains(event.eventType())||repository.existsByEventId(event.eventId()))return; try{Map<String,Object> raw=mapper.readValue(event.payload(),new TypeReference<>(){}); Instant now=Instant.now(); repository.save(new ArchiveOsRuntimeDeliveryEntity(event.eventId(),event.idempotencyKey(),text(raw,"correlationId"),nullable(raw,"causationId"),nullable(raw,"orderId"),nullable(raw,"simulationRunId"),entityId(event,raw),event.eventType().name(),mapper.writeValueAsString(payload(event,raw)),now));}catch(Exception ignored){/* observability delivery must never affect manufacturing */}}
    @Transactional(propagation=Propagation.REQUIRES_NEW)
    public void snapshotMarket(String eventId,String idempotencyKey,String correlationId,String causationId,String orderId,String simulationRunId,String entityId,String eventType,Instant occurredAt,Map<String,Object> metadata){if(repository.existsByEventId(eventId))return;try{Map<String,Object> body=new LinkedHashMap<>();body.put("sourceSystem","archive-nexus");body.put("targetSystem","archive-nexus");body.put("eventId",eventId);body.put("correlationId",correlationId);body.put("entityId",entityId);body.put("eventType",eventType);body.put("occurredAt",occurredAt.toString());put(body,"orderId",orderId);put(body,"causationId",causationId);put(body,"simulationRunId",simulationRunId);body.put("metadata",allow(metadata));Instant now=Instant.now();repository.save(new ArchiveOsRuntimeDeliveryEntity(eventId,idempotencyKey,correlationId,causationId,orderId,simulationRunId,entityId,eventType,mapper.writeValueAsString(body),now));}catch(Exception ignored){}}
    @Transactional public void publishBatch(){if(!properties.enabled)return;recoverStale(); List<ArchiveOsRuntimeDeliveryEntity> list=repository.findDeliverable(Instant.now(),PageRequest.of(0,properties.batchSize)); for(ArchiveOsRuntimeDeliveryEntity e:list) publish(e);}
    @Transactional public void recoverStale(){Instant now=Instant.now();repository.findAllByStatusAndPublishingStartedAtBefore(ArchiveOsRuntimeDeliveryStatus.PUBLISHING,now.minus(properties.stalePublishing)).forEach(e->e.recoverStale(now));}
    private void publish(ArchiveOsRuntimeDeliveryEntity e){Instant now=Instant.now();e.publishing(now);ArchiveOsRuntimePublisher.PublishOutcome outcome=publisher.publish(e);switch(outcome.kind()){case SUCCESS->e.published(now);case DISABLED->e.terminal(ArchiveOsRuntimeDeliveryStatus.PENDING,"DISABLED","Runtime ingest disabled",now);case CONFIG->e.terminal(ArchiveOsRuntimeDeliveryStatus.CONFIG_ERROR,outcome.code(),outcome.message(),now);case NON_RETRYABLE->e.terminal(ArchiveOsRuntimeDeliveryStatus.NON_RETRYABLE_ERROR,outcome.code(),outcome.message(),now);case RETRY->{if(e.retryCount()+1>=properties.maxRetry)e.terminal(ArchiveOsRuntimeDeliveryStatus.FAILED,outcome.code(),outcome.message(),now);else e.retry(outcome.code(),outcome.message(),now.plus(properties.retryDelay.multipliedBy(Math.max(1,e.retryCount()+1))),now);}}}
    @Transactional(readOnly=true) public Summary summary(){Map<String,Long> counts=new LinkedHashMap<>();for(ArchiveOsRuntimeDeliveryStatus s:ArchiveOsRuntimeDeliveryStatus.values())counts.put(s.name(),repository.countByStatus(s));return new Summary(properties.enabled,counts,repository.count());}
    @Transactional(readOnly=true) public List<View> events(String status,String correlationId,int limit){List<ArchiveOsRuntimeDeliveryEntity> list=correlationId!=null&&!correlationId.isBlank()?repository.findAllByCorrelationIdOrderByCreatedAtAsc(correlationId,PageRequest.of(0,safe(limit))): status==null?repository.findAll(PageRequest.of(0,safe(limit))).getContent():repository.findAllByStatusOrderByCreatedAtDesc(ArchiveOsRuntimeDeliveryStatus.valueOf(status),PageRequest.of(0,safe(limit)));return list.stream().map(this::view).toList();}
    @Transactional(readOnly=true) public Preview preview(String correlationId){List<ArchiveOsRuntimeDeliveryEntity> list=repository.findAllByCorrelationIdOrderByCreatedAtAsc(correlationId,PageRequest.of(0,500));Map<String,Long> counts=new LinkedHashMap<>();for(ArchiveOsRuntimeDeliveryStatus s:ArchiveOsRuntimeDeliveryStatus.values())counts.put(s.name(),list.stream().filter(e->e.status()==s).count());long routeSkipped=list.stream().filter(e->e.payloadJson().contains("ROUTE_SKIPPED")||e.payloadJson().contains("\"targetSystem\":\"NONE\"")).count();return new Preview(correlationId,list.size(),list.size(),counts.get("PENDING"),counts.get("PUBLISHING"),counts.get("PUBLISHED"),counts.get("RETRY_WAIT"),counts.get("FAILED")+counts.get("NON_RETRYABLE_ERROR"),counts.get("CONFIG_ERROR"),list.stream().filter(e->e.causationId()==null).count(),list.stream().filter(e->e.orderId()!=null).count(),list.stream().filter(e->e.orderId()==null).count(),counts.get("PUBLISHED"),list.stream().filter(e->e.payloadJson().contains("businessPublishable")).count(),list.stream().filter(e->e.payloadJson().contains("archive-logistics")).count(),list.stream().filter(e->e.payloadJson().contains("archive-ledger")).count(),routeSkipped);}
    private Map<String,Object> payload(OutboxEventEntity e,Map<String,Object> raw){Map<String,Object> b=new LinkedHashMap<>();b.put("sourceSystem","archive-nexus");b.put("targetSystem",target(e.targetService()));b.put("eventId",e.eventId());put(b,"correlationId",text(raw,"correlationId"));b.put("entityId",entityId(e,raw));b.put("eventType",e.eventType().name());b.put("occurredAt",e.occurredAt().toString());put(b,"orderId",nullable(raw,"orderId"));put(b,"causationId",nullable(raw,"causationId"));put(b,"simulationRunId",nullable(raw,"simulationRunId"));b.put("metadata",allow(raw));return b;}
    private String entityId(OutboxEventEntity e,Map<String,Object> raw){String v=nullable(raw,"entityId");return v!=null?v:e.aggregateId();} private String target(OutboxTargetService t){return t==OutboxTargetService.LOGITICS?"archive-logistics":t==OutboxTargetService.LEDGER?"archive-ledger":"archive-nexus";} private static String text(Map<String,Object> m,String k){return nullable(m,k);} private static String nullable(Map<String,Object> m,String k){Object v=m.get(k);return v==null||v.toString().isBlank()?null:v.toString();} private static void put(Map<String,Object> m,String k,Object v){if(v!=null)m.put(k,v);} private static Map<String,Object> allow(Map<String,Object> raw){Map<String,Object> m=new LinkedHashMap<>();for(String k:List.of("productionOrderId","productionRequestId","batchId","workCenterId","materialType","qualityStatus","defectCategory","backlogCount","riskLevel","shipmentId","factoryId","quantity","priority","productivityScore","usedCapacity","bottleneckRole")){if(raw.get(k)!=null)m.put(k,raw.get(k));}return m;} private int safe(int l){return Math.max(1,Math.min(l,200));} private View view(ArchiveOsRuntimeDeliveryEntity e){return new View(e.eventId(),e.correlationId(),e.orderId(),e.entityId(),e.eventType(),e.status().name(),e.retryCount(),e.lastErrorCode(),e.lastErrorMessage(),e.publishedAt(),e.createdAt());}
    public record Summary(boolean enabled,Map<String,Long> status,long total){} public record View(String eventId,String correlationId,String orderId,String entityId,String eventType,String status,int retryCount,String lastErrorCode,String lastErrorMessage,Instant publishedAt,Instant createdAt){} public record Preview(String correlationId,long totalEvents,long observableEvents,long pending,long publishing,long published,long retrying,long failed,long configError,long rootEvents,long eventsWithOrderId,long eventsWithoutOrderId,long alreadyDelivered,long businessPublishableEvents,long logisticsPublishableEvents,long ledgerPublishableEvents,long routeSkippedEvents){}
}
