package com.archivenexus.backend.task;

import com.archivenexus.backend.archiveos.*;import com.archivenexus.backend.audit.AuditService;
import com.archivenexus.backend.task.NexusTaskModels.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Qualifier;import org.springframework.core.task.TaskExecutor;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;import java.util.*;

@Service
public class NexusTaskService {
 private final NexusTaskRepository tasks;private final NexusTaskLogRepository logs;private final TaskStateStore state;private final NexusTaskRunner runner;private final TaskExecutor executor;private final ArchiveOsWorkflowClient workflows;private final ObjectMapper mapper;private final AuditService audit;
 public NexusTaskService(NexusTaskRepository tasks,NexusTaskLogRepository logs,TaskStateStore state,NexusTaskRunner runner,@Qualifier("nexusTaskExecutor") TaskExecutor executor,ArchiveOsWorkflowClient workflows,ObjectMapper mapper,AuditService audit){this.tasks=tasks;this.logs=logs;this.state=state;this.runner=runner;this.executor=executor;this.workflows=workflows;this.mapper=mapper;this.audit=audit;}
 @Transactional public TaskResponse create(CreateTaskRequest r){Instant now=Instant.now();NexusTaskEntity t=tasks.save(new NexusTaskEntity("TASK-"+UUID.randomUUID().toString().substring(0,12).toUpperCase(),r.title().trim(),r.type(),blank(r.factoryId()),blank(r.question()),value(r.requestedBy(),"operator"),r.maxAttempts()==null?3:r.maxAttempts(),now));logs.save(new NexusTaskLogEntity(t.id(),"INFO","작업 초안이 생성되었습니다.",now));audit.record(t.requestedBy(),"TASK_DRAFT_CREATED","Task draft created",t.id(),t.correlationId(),null,Map.of("type",t.type().name()));return response(t);}
 public List<TaskResponse> findAll(){return tasks.findAllByOrderByCreatedAtDesc().stream().map(this::response).toList();}
 public Optional<TaskDetailResponse> findById(String id){return tasks.findById(id).map(t->new TaskDetailResponse(response(t),findLogs(id)));}
 public List<TaskLogResponse> findLogs(String id){return logs.findAllByTaskIdOrderByCreatedAtAsc(id).stream().map(l->new TaskLogResponse(l.id(),l.taskId(),l.level(),l.message(),l.createdAt())).toList();}
 public Optional<TaskResponse> run(String id){NexusTaskEntity task=tasks.findById(id).orElse(null);if(task==null)return Optional.empty();if(!Set.of(TaskStatus.DRAFT,TaskStatus.RETRY_REQUESTED).contains(task.status()))return Optional.of(response(task));try{ArchiveOsWorkflowClient.WorkflowRef workflow=workflows.create(task);state.attachWorkflow(id,workflow.id());state.startAnalysis(id);executor.execute(()->runner.execute(id));}catch(RuntimeException error){state.retryRequested(id,"ArchiveOS unavailable: "+error.getMessage());}return tasks.findById(id).map(this::response);}
 public Optional<TaskResponse> sync(String id){NexusTaskEntity task=tasks.findById(id).orElse(null);if(task==null)return Optional.empty();if(task.workflowId()==null)return Optional.of(response(task));try{ArchiveOsWorkflowClient.WorkflowRef workflow=workflows.get(task.workflowId());if("approved".equals(workflow.status())&&task.status()==TaskStatus.WAITING_APPROVAL){state.approve(id,workflow.approvalId());executor.execute(()->runner.resumeApproved(id));}else if("rejected".equals(workflow.status())&&task.status()==TaskStatus.WAITING_APPROVAL){state.reject(id,workflow.approvalId());}}catch(RuntimeException error){audit.record("system","WORKFLOW_SYNC_FAILED",error.getMessage(),task.id(),task.correlationId(),task.workflowId(),Map.of());}return tasks.findById(id).map(this::response);}
 @Scheduled(fixedDelayString="${archive-nexus.archiveos.workflow.sync-delay-ms:5000}") public void syncWaitingApprovals(){tasks.findAllByStatus(TaskStatus.WAITING_APPROVAL).forEach(task->sync(task.id()));}
 @Transactional public Optional<TaskResponse> cancel(String id){return tasks.findById(id).filter(t->!Set.of(TaskStatus.SUCCESS,TaskStatus.FAILED,TaskStatus.REJECTED,TaskStatus.CANCELLED).contains(t.status())).map(t->{t.cancel(Instant.now());logs.save(new NexusTaskLogEntity(id,"WARN","운영자가 작업을 중단했습니다.",Instant.now()));audit.record(t.requestedBy(),"TASK_CANCELLED","Operator cancellation",id,t.correlationId(),t.workflowId(),Map.of());return response(t);});}
 @Transactional public Optional<TaskResponse> retry(String id){return tasks.findById(id).filter(t->Set.of(TaskStatus.FAILED,TaskStatus.CANCELLED,TaskStatus.REJECTED,TaskStatus.RETRY_REQUESTED).contains(t.status())&&t.attemptCount()<t.maxAttempts()).map(t->{t.resetForRetry(Instant.now());logs.save(new NexusTaskLogEntity(id,"INFO","재시도가 요청되었습니다.",Instant.now()));return response(t);});}
 private TaskResponse response(NexusTaskEntity t){return new TaskResponse(t.id(),t.title(),t.type(),t.factoryId(),t.question(),t.requestedBy(),t.status(),t.attemptCount(),t.maxAttempts(),t.resultSummary(),read(t.evidenceJson(),new TypeReference<>(){}),read(t.recommendationJson(),new TypeReference<>(){}),t.confidence(),t.correlationId(),t.workflowId(),t.approvalId(),t.rpaTaskId(),t.errorMessage(),t.createdAt(),t.startedAt(),t.completedAt(),t.updatedAt());}
 private <T>T read(String json,TypeReference<T> type){try{return json==null?mapper.readValue("[]",type):mapper.readValue(json,type);}catch(Exception error){try{return mapper.readValue("[]",type);}catch(Exception impossible){throw new IllegalStateException(impossible);}}}
 private String blank(String v){return v==null||v.isBlank()?null:v.trim();}private String value(String v,String f){return v==null||v.isBlank()?f:v.trim();}
}
