global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: archive-nexus-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - archive-nexus-backend:8080
