package com.archivenexus.backend.ai;
import com.archivenexus.backend.ai.ManufacturingAiModels.Intent;import org.springframework.ai.chat.model.ChatModel;import org.springframework.beans.factory.ObjectProvider;import org.springframework.stereotype.Component;import java.util.*;
@Component public class IntentRouter{
 private final ChatModel chatModel;public IntentRouter(ObjectProvider<ChatModel> provider){this.chatModel=provider.getIfAvailable();}
 public List<Intent> route(String question){if(chatModel!=null){try{String answer=chatModel.call("Classify into comma-separated PRODUCTION, QUALITY, MAINTENANCE, INVENTORY, LOGISTICS, CROSS_DOMAIN, UNKNOWN. Question: "+question);List<Intent> result=parseModelResponse(answer);if(!result.isEmpty()&&!result.equals(List.of(Intent.UNKNOWN)))return result;}catch(RuntimeException ignored){}}return routeByRule(question);}
 List<Intent> routeByRule(String question){String q=question==null?"":question.toLowerCase(Locale.ROOT);Set<Intent> out=new LinkedHashSet<>();if(any(q,"생산","생산량","실적","목표","병목","production","output","throughput"))out.add(Intent.PRODUCTION);if(any(q,"품질","불량","검사","lot","quality","defect","yield"))out.add(Intent.QUALITY);if(any(q,"설비","정비","진동","온도","전류","고장","maintenance","vibration","temperature","machine"))out.add(Intent.MAINTENANCE);if(any(q,"재고","안전재고","원자재","부족","inventory","stock","material"))out.add(Intent.INVENTORY);if(any(q,"물류","출하","배송","납기","지연","logistics","shipment","delivery"))out.add(Intent.LOGISTICS);if(any(q,"근본 원인","연쇄","종합 원인","전체 영향","root cause","cross domain","end-to-end")||out.size()>=3)out.add(Intent.CROSS_DOMAIN);return out.isEmpty()?List.of(Intent.UNKNOWN):List.copyOf(out);}
 private List<Intent> parseModelResponse(String value){if(value==null||value.isBlank())return List.of();Set<Intent> out=new LinkedHashSet<>();String q=value.toUpperCase(Locale.ROOT);for(Intent i:Intent.values())if(q.contains(i.name()))out.add(i);if(out.size()>1)out.remove(Intent.UNKNOWN);return new ArrayList<>(out);}
 private boolean any(String value,String...keys){for(String key:keys)if(value.contains(key))return true;return false;}
}
