import {useEffect,useState} from 'react';import {Bot,CircleStop,Play,RotateCcw} from 'lucide-react';import {api} from './api';import type {Factory,NexusTask,NexusTaskLog,NexusTaskType} from './types';
export function TaskOperationsPanel({factories,tasks,onChanged}:{factories:Factory[];tasks:NexusTask[];onChanged:()=>Promise<void>}){
 const [title,setTitle]=useState('제조 운영 분석'),[type,setType]=useState<NexusTaskType>('MANUFACTURING_QUERY'),[factoryId,setFactoryId]=useState(''),[question,setQuestion]=useState('생산, 품질, 설비 상태를 종합 분석해줘'),[selectedId,setSelectedId]=useState<string|null>(tasks[0]?.id??null),[logs,setLogs]=useState<NexusTaskLog[]>([]),[pending,setPending]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!selectedId&&tasks.length)setSelectedId(tasks[0].id);},[selectedId,tasks]);useEffect(()=>{if(!selectedId){setLogs([]);return;}void api.taskLogs(selectedId).then(setLogs).catch(()=>setLogs([]));},[selectedId,tasks]);
 const act=async(action:()=>Promise<unknown>)=>{setPending(true);try{await action();await onChanged();setError('');}catch(c){setError(c instanceof Error?c.message:'작업 요청에 실패했습니다.');}finally{setPending(false);}};
 const create=async()=>{if(!title.trim()||(type==='MANUFACTURING_QUERY'&&!question.trim()))return;await act(async()=>{const t=await api.createTask({title,type,factoryId:factoryId||undefined,question:type==='MANUFACTURING_QUERY'?question:undefined,requestedBy:'operator'});setSelectedId(t.id);});};
 const selected=tasks.find(t=>t.id===selectedId)??null;
 return <div className="task-workspace"><section className="panel"><div className="panel-title"><h2><Bot size={17}/>운영 작업 생성</h2></div><div className="task-form"><label>작업 이름<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>실행 유형<select value={type} onChange={e=>setType(e.target.value as NexusTaskType)}><option value="MANUFACTURING_QUERY">Manufacturing Agent 분석</option><option value="SIMULATOR_TICK">Simulator Tick 생성</option></select></label><label>공장<select value={factoryId} onChange={e=>setFactoryId(e.target.value)}><option value="">전체 공장</option>{factories.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>{type==='MANUFACTURING_QUERY'&&<label>질문<textarea rows={5} value={question} onChange={e=>setQuestion(e.target.value)}/></label>}<button disabled={pending} onClick={()=>void create()}>작업 만들기</button>{error&&<p className="error-text" role="alert">{error}</p>}</div></section>
 <section className="panel"><div className="panel-title"><h2>작업 상태</h2><span>{tasks.length}</span></div><div className="task-list">{tasks.length===0?<div className="empty-state">생성된 작업이 없습니다.</div>:tasks.map(t=><button className={`task-row ${selectedId===t.id?'selected':''}`} key={t.id} onClick={()=>setSelectedId(t.id)}><span><strong>{t.title}</strong><small>{t.id} · {t.type}</small></span><TaskStatus value={t.status}/></button>)}</div></section>
 <section className="panel full"><div className="panel-title"><h2>작업 상세와 실행 로그</h2>{selected&&<TaskStatus value={selected.status}/>}</div>{!selected?<div className="empty-state">확인할 작업을 선택하세요.</div>:<><div className="task-detail-header"><div><strong>{selected.title}</strong><p>{selected.resultSummary??selected.errorMessage??selected.question??'실행 대기 중'}</p><small>시도 {selected.attemptCount}/{selected.maxAttempts} · 요청자 {selected.requestedBy}</small></div><div className="inline-actions">{selected.status==='PENDING'&&<button disabled={pending} onClick={()=>void act(()=>api.runTask(selected.id))}><Play size={15}/>실행</button>}{['PENDING','RUNNING'].includes(selected.status)&&<button className="reject" disabled={pending} onClick={()=>void act(()=>api.cancelTask(selected.id))}><CircleStop size={15}/>중단</button>}{['FAILED','CANCELLED'].includes(selected.status)&&selected.attemptCount<selected.maxAttempts&&<button disabled={pending} onClick={()=>void act(()=>api.retryTask(selected.id))}><RotateCcw size={15}/>재시도</button>}</div></div><div className="task-logs">{logs.length===0?<div className="empty-state">아직 실행 로그가 없습니다.</div>:logs.map(l=><div key={l.id} className={`task-log ${l.level.toLowerCase()}`}><time>{formatDate(l.createdAt)}</time><strong>{l.level}</strong><span>{l.message}</span></div>)}</div></>}</section></div>;
}
function TaskStatus({value}:{value:string}){const tone=value==='FAILED'?'danger':['PENDING','RUNNING','CANCELLED'].includes(value)?'warning':'success';return <span className={`status-badge ${tone}`}>{value}</span>;}
function formatDate(value:string){return new Intl.DateTimeFormat('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value));}
